### PR TITLE
Remove ResourceInfo and convert to ResourceMetadata

### PR DESCRIPTION
**Pull request by KJoslyn**
Supports jvm [#495](https://github.com/WycliffeAssociates/otter-jvm/pull/495)

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/129)

### CODE REVIEW

**Review by aunger — APPROVED** [review]
ResourceInfo was intentionally different than ResourceMetadata: just what was needed in the workbook model, simpler, without a database row id. This seems like a step backwards.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/129#-:-LnyIbHiC4phO_gCBgqe:bplffm0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by aunger — CHANGES_REQUESTED** [review]
Not sure why Reviewable thought that was an LGTM message. 

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/129#-:-LnyJ3Kg4N9I4_rFKphc:bz189uc)* status: all files reviewed, 1 unresolved discussion (waiting on @KJoslyn)

*[a discussion](https://reviewable.io/reviews/wycliffeassociates/otter-common/129#-LnyJHGdC6imPCYKQe9k:-LnyJHGdC6imPCYKQe9l:bplffm0) (no related file):*
ResourceInfo was intentionally different than ResourceMetadata: just what was needed in the workbook model, simpler, without a database row id. This seems like a step backwards.

---

**Review by aunger — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/129)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by aunger — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/129)* status: all files reviewed, 1 unresolved discussion (waiting on @KJoslyn)

**Review by jsarabia — APPROVED** [review]

**Review by aunger — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/129#-:-Lo106Xn5FgzCatBjCzz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KJoslyn)

**Review by jsarabia — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/129)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @aunger)

*[a discussion](https://reviewable.io/reviews/wycliffeassociates/otter-common/129#-LnyJHGdC6imPCYKQe9k:-LoM3G5s9enb9sJ7Ym_Z:b8hwikl) (no related file):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

ResourceInfo was intentionally different than ResourceMetadata: just what was needed in the workbook model, simpler, without a database row id. This seems like a step backwards.
</blockquote></details>

Based on conversation, we've made variables in ResourceMetadata immutable as a compromise here

---

**Review by jsarabia — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/129#-:-LoM3U6v5DhyZiLHeZmo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
