### PR TITLE
Navigation interfaces

### PR DESCRIPTION
**Pull request by KJoslyn**
Support for jvm [#489](https://github.com/WycliffeAssociates/otter-jvm/pull/489).

This change is [Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)

### CODE REVIEW

**Review by aunger — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @aunger, @KJoslyn, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ResourceInfo.kt, line 6 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnPInhJ1VJ_3S_Jj9BR:-LnPInhJ1VJ_3S_Jj9BS:b-d7ngab) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/7b8b018ca0facd07661c9e9d238014b7b3cff7f6/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ResourceInfo.kt#L6)):*
> ```Kotlin
>     val slug: String,
>     val title: String,
>     val type: String
> ```

I'm unsure: should this be an enum instead of string?
___
*[src/main/kotlin/org/wycliffeassociates/otter/common/navigation/ITabGroupBuilder.kt, line 22 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnPIQR79thpNQZpaZDS:-LnPIQR79thpNQZpaZDT:b-dtr92d) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/7b8b018ca0facd07661c9e9d238014b7b3cff7f6/src/main/kotlin/org/wycliffeassociates/otter/common/navigation/ITabGroupBuilder.kt#L22)):*
> ```Kotlin
>     fun createRecordScriptureTabGroup(): ITabGroup
> 
>     fun createRecordResourceTabGroup(): ITabGroup
> ```

Nit: `build*TabGroup()` to match `build()` above

**Review by KJoslyn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @aunger and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ResourceInfo.kt, line 6 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnPInhJ1VJ_3S_Jj9BR:-LnT-TjxEfjzzRI9L0RY:bryet4e) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/7b8b018ca0facd07661c9e9d238014b7b3cff7f6/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ResourceInfo.kt#L6)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

I'm unsure: should this be an enum instead of string?
</blockquote></details>

It probably should be- not sure where it should go though. +@sarabiaj  
___
*[src/main/kotlin/org/wycliffeassociates/otter/common/navigation/ITabGroupBuilder.kt, line 22 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnPIQR79thpNQZpaZDS:-LnT0hMo2ncxXsaOpDaR:bv0jxid) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/7b8b018ca0facd07661c9e9d238014b7b3cff7f6/src/main/kotlin/org/wycliffeassociates/otter/common/navigation/ITabGroupBuilder.kt#L22)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

Nit: `build*TabGroup()` to match `build()` above
</blockquote></details>

True, done.

**Review by aunger — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @aunger, @KJoslyn, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ResourceInfo.kt, line 6 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnPInhJ1VJ_3S_Jj9BR:-LnTjO50-DmJyrdhkzuX:b-sy3pxw) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/7b8b018ca0facd07661c9e9d238014b7b3cff7f6/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ResourceInfo.kt#L6)):*
<details><summary><i>Previously, KJoslyn wrote…</i></summary><blockquote>

It probably should be- not sure where it should go though. +@sarabiaj  
</blockquote></details>

It could probably just be its own file in this workbook package.

**Review by jsarabia — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @aunger, @KJoslyn, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Book.kt, line 13 at r2](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnZ3gHgBTnrvTx4V0U8:-LnZ3gHhEzGCycapjjSZ:bz9jeg0) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/f920d68945e10559efb73a8a8de7ec0b28c4b8fc/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Book.kt#L13)):*
> ```Kotlin
>     val title: String,
>     val chapters: Observable<Chapter>,
>     val resourceContainer: ResourceMetadata,
> ```

This isn't a ResourceContainer, please don't call it such.
Metaphorically, It's a soda, and it could be any soda. I don't want to restrict ourselves to Pepsi, or make people working with this assume it's Pepsi. If I see Pepsi, I assume it's a brown cola; but am going to be utterly confused at how to handle a clear soda when it's Sprite.
___
*[src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ResourceInfo.kt, line 6 at r1](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnPInhJ1VJ_3S_Jj9BR:-LnZ-1FtCFcAEXTB8Xb2:bwqvsn1) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/7b8b018ca0facd07661c9e9d238014b7b3cff7f6/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/ResourceInfo.kt#L6)):*
<details><summary><i>Previously, aunger (Russell Aunger) wrote…</i></summary><blockquote>

It could probably just be its own file in this workbook package.
</blockquote></details>

I'd just assume keep it a string for now.
Part of me is unsure why we even have this object rather than just use the ResourceMetadata anyway.

Otter's data schema allows ResourceContainers to be mapped to it, but it is not a direct implementation of the ResourceContainer spec (or any other container format for that matter)- and that's by design. A positive side effect of this is that Scripture Burrito is already treated equally in this sense. 

The enum belongs higher up (common, data package); and the ResourceMetadata class should have type be an enum rather than a string. This should have been done at the beginning, and should have been the case with regards to the kotlin resource container library.

So I don't disagree that the ideal is that it be an enum. But it involves mappers and refactoring, and we may as well wait for more support for Scripture Burrito to even see what list of types make sense.

I don't like "tribal types", that only exist within a domain package for limited reason. Things like workbook, book, chapter, chunk are valuable because dealing with content and collection is too unwieldy and workbook, book, chapter, chunk help us reason about the problems we're solving within this space/domain. But when we can reuse our core datatypes that makes the most sense to me. That's also part of why I feel like this should just straight up be the ResourceMetadata object to begin with. Never mind the fact that the RM object is probably in memory already and the info object here has been created and mapped to from it, increasing our memory cost for an object that is strictly a subset. If you want to really limit data access (and have a real need and reason to) you could at least have ResourceInfo be a base class, ResourceMetadata be the subclass, and only pass along the object as a ResourceInfo. I'm not saying we should do that though, I still feel like it's unnecessary.
___
*[src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt, line 47 at r2](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnZ4MA37kjFJHs8odmu:-LnZ4MA37kjFJHs8odmv:byr4ffv) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/f920d68945e10559efb73a8a8de7ec0b28c4b8fc/src/main/kotlin/org/wycliffeassociates/otter/common/persistence/repositories/WorkbookRepository.kt#L47)):*
> ```Kotlin
>     }
> 
>     private fun Collection.getResourceContainer() = this.resourceContainer
> ```

see above

**Review by KJoslyn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @aunger, @KJoslyn, and @sarabiaj)

___
*[src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Book.kt, line 13 at r2](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnZ3gHgBTnrvTx4V0U8:-LnZB1PD-ergGFkp7RH4:b53ftjz) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/f920d68945e10559efb73a8a8de7ec0b28c4b8fc/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Book.kt#L13)):*
<details><summary><i>Previously, sarabiaj (Joe) wrote…</i></summary><blockquote>

This isn't a ResourceContainer, please don't call it such.
Metaphorically, It's a soda, and it could be any soda. I don't want to restrict ourselves to Pepsi, or make people working with this assume it's Pepsi. If I see Pepsi, I assume it's a brown cola; but am going to be utterly confused at how to handle a clear soda when it's Sprite.
</blockquote></details>

How about just resourceMetadata then?

**Review by aunger — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)* status: all files reviewed, 2 unresolved discussions (waiting on @KJoslyn and @sarabiaj)

**Review by jsarabia — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)* status: all files reviewed, 2 unresolved discussions (waiting on @KJoslyn)

___
*[src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Book.kt, line 13 at r2](https://reviewable.io/reviews/wycliffeassociates/otter-common/124#-LnZ3gHgBTnrvTx4V0U8:-Lo0jFVHEVhyG08ExeMJ:b2zaubx) ([raw file](https://github.com/wycliffeassociates/otter-common/blob/f920d68945e10559efb73a8a8de7ec0b28c4b8fc/src/main/kotlin/org/wycliffeassociates/otter/common/data/workbook/Book.kt#L13)):*
<details><summary><i>Previously, KJoslyn wrote…</i></summary><blockquote>

How about just resourceMetadata then?
</blockquote></details>

FYI: could just be metadata, but yes that's fine

**Review by jsarabia — APPROVED** [review]
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/wycliffeassociates/otter-common/124)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
